[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
FewBodyHamiltonians = "3a126c26-e5d7-4a95-83c3-3b69f8a11ded"
Optim = "429524aa-4258-5aef-a3af-852621145aeb"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
QuasiMonteCarlo = "8a4e6c94-4038-4cdc-81c3-7e6ffdb2a71b"

[compat]
Optim = "1.7.8"
Plots = "1.39.0"
julia = "1.8.5"
